<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MAVBCP139" name="calculatorTest.Assertclass" tests="8" failures="1" timestamp="2020-07-03T10:26:14 IST" time="0.034" errors="0">
  <testcase name="exponent" time="0.003" classname="calculatorTest.Assertclass"/>
  <system-out/>
  <testcase name="inverse" time="0.003" classname="calculatorTest.Assertclass"/>
  <system-out/>
  <testcase name="mod" time="0.002" classname="calculatorTest.Assertclass"/>
  <system-out/>
  <testcase name="add" time="0.015" classname="calculatorTest.Assertclass"/>
  <system-out>
Addition operation is successful  </system-out>
  <testcase name="div" time="0.004" classname="calculatorTest.Assertclass"/>
  <system-out/>
  <testcase name="negate" time="0.002" classname="calculatorTest.Assertclass"/>
  <system-out/>
  <testcase name="sub" time="0.003" classname="calculatorTest.Assertclass">
    <failure type="java.lang.AssertionError" message="Subraction operation Failed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Subraction operation Failed expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertFalse(Assert.java:65)
at calculatorTest.Assertclass.sub(Assertclass.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- sub -->
  <system-out/>
  <testcase name="mul" time="0.002" classname="calculatorTest.Assertclass"/>
  <system-out/>
</testsuite> <!-- calculatorTest.Assertclass -->
